on:
  pull_request:
    branches:
      - development
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Dependencies
      run: npm install

    - name: Populate Block List
      run: npm run populate

    - name: Give Execute Permission to Script
      run: chmod +x ./scripts/check_new.sh

    - name: Check new block
      id: check_block
      run: |
        new_blocks=$(./scripts/check_new.sh)
        echo "NEW_BLOCKS=$new_blocks" >> $GITHUB_ENV  # Set environment variable

    - name: Lint and Test
      run: npm run lint

    - name: Echo Test
      run: echo $NEW_BLOCKS

