on:
  pull_request:
    branches:
      - development
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Dependencies
      run: npm install

    - name: Populate Block List
      run: npm run populate

    - name: Give Execute Permission to Script
      run: chmod +x ./scripts/check_new.sh

    - name: Check new block
      id: check_block
      run: |
        new_blocks=$(./scripts/check_new.sh)
        echo "NEW_BLOCKS=$new_blocks" >> $GITHUB_ENV  # Set environment variable

    - name: Lint and Test
      run: npm run lint

    - name: Build Angular Library
      run: npm run build

    - name: Notify Slack
      if: env.NEW_BLOCKS != ''
      uses: slackapi/slack-github-action@v1.23.0
      with:
        payload: |
          {
            "text": "🚀 A new block/component has been added: ${env.NEW_BLOCKS}.
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
